name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    services:
      docker:
        image: docker:19.03.12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

    - name: Build and Push Docker Image
      run: |
        docker build -t music_identifier:latest .
